# Generated by Django 5.0.1 on 2024-03-19 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerebro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='respuesta',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='texto',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='parts',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
