# Generated by Django 5.0.1 on 2024-03-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerebro', '0002_rename_respuesta_pregunta_role_remove_pregunta_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='fecha',
        ),
    ]
